### ISSUE TITLE
REST API to lookup the tare weight of a container

### ISSUE THREAD

**Issue by AltiusRupert** [bic-org/Boxtech#1]
Set up an API to look up the tare weight of a container.

This is a REST API. Authentication is through OAuth2.

Parameters for the request are the container number, as well as the requested weight unit (kgs, lbs).
The answer is the weight, a decimal value in kgs or lbs. Decimal point is a '.'.

Error codes : 
- authentication error : standard web REST codes
- container not present in the TCD database

**Comment by bic-boxtech** [comment]
This service is now implemented and documented : refer to the README page as well as to the Wiki pages for details on implementation.
Questions will be addressed here.
