### ISSUE TITLE
no-such-app

### ISSUE THREAD

**Issue by StefanoPaparesta** [bic-org/Boxtech#11]
Hello, i have tried with postman with the test endpoint but heroku catch an error

no-such-app...

What is wong  ?

Stefano

**Comment by BernierSFCloud** [comment]
Hello @StefanoPaparesta ,

during the migration to v2 the test URL changed. It was not updated everywhere in the document.

The correct URL is [bic-tcd-test.herokuapp.com](bic-tcd-test.herokuapp.com)

I have corrected the URL in the documentation. You should be able to follow it without any problem.
