### ISSUE TITLE
Error /oauth/token in test

### ISSUE THREAD

**Issue by StefanoPaparesta** [bic-org/Boxtech#12]
i use this endpoint http://bic-tcd-test.herokuapp.com/oauth/token
receive this error
{
    "statusCode": 400,
    "status": 400,
    "code": 400,
    "message": "Invalid request: method must be POST",
    "name": "invalid_request"
}

I have correctly set header and body in postman in accord with your guide.
Wath is wrong ?

**Comment by StefanoPaparesta** [comment]
Sorry, any new with this issue, i can't develop the integration with your API ?
Regards
Stefano

**Comment by nostrum-service** [comment]
I have use this endpoint to get token
https://app.bic-boxtech.org/oauth/token
with POST method - it works

**Comment by StefanoPaparesta** [comment]
Sorry in  #11 issue the correct endpoint is http://bic-tcd-test.herokuapp.com/oauth/token, i don't undertstand this difference

**Comment by AltiusRupert** [comment]
Hi @StefanoPaparesta ,
You can use a test endpoint to verify that your program is working : that is http://bic-tcd-test.herokuapp.com/oauth/token .

When you put your program into production, you will want to call the production Boxtech database : that is https://app.bic-boxtech.org/oauth/token .

HTH
