### ISSUE TITLE
Error query web application

### ISSUE THREAD

**Issue by StefanoPaparesta** [bic-org/Boxtech#13]
When make a query 
https://bic-tcd-test.herokuapp.com/containers?search=EISU3526339

receive an error

"You cannot query EISU more than null times a day"

**Comment by cmsdroff** [comment]
@StefanoPaparesta for info if you use the production API this will work, it's an issue within test environment in my experience.

**Comment by bic-boxtech** [comment]
@StefanoPaparesta I'm closing the issue due to time passed, please open a new issue and we will be happy to support you in future.
