### ISSUE TITLE
Query Limit

### ISSUE THREAD

**Issue by primmslim** [bic-org/Boxtech#14]
Hi,

Just tried running the API to update the container details in our Database and it says i've already hit the limit of 100 per "abcd" container for the day.
Is there any plans to remove the limit ? 

Thanks

**Comment by AltiusRupert** [comment]
There is a limit on the number of queries for the same BIC CODE made every day.
If you are testing, you may use another BIC Code.
If not, could you tell us why you would like to look up the same BI Code more tan 100 times a day ?  This will help us adjust the limit.

**Comment by blortorbis** [comment]
We'd also be interested in a larger scale implementation to augment our current records and to expand requests to include Manufactured dates.

**Comment by ttohu** [comment]
It would be very useful to query a larger amount of Container IDs, e.g. see all the reefer codes from one provider, match those with empty/full tracing, and negotiate contingents of empty containers.
I think a simple "list all container codes and type from one container provider" type of API call would be great. You could ask for no more than 2-3 fields, and get a longer list. The detailed data query of one container would be great if you already after selected containers.

**Comment by cmsdroff** [comment]
@blortorbis @primmslim @ttohu, it would be good if you have some user stories/use cases to detail them as an issue so we can consider as a feature request for Boxtech.  

I can then consider these and discuss within BIC to address where possible.

**Comment by craig-kotahi** [comment]
@cmsdroff to provide a use case.   

We are a logistics service provider primarily focused on ocean shipments.  We receive event information from various sources that allows us to track the movement of containers.  Often this event information lacks any detail about the container so would  to enrich these events using an additional data source like your API.

Here are some of our recent daily aggregates:

![image](https://user-images.githubusercontent.com/79610667/109233802-5fbdc380-782f-11eb-8006-ff6e52536dfe.png)

Now we can (and would) cache results for a reasonable time (e.g. 30 days), so the number of calls to your API would be less however it's fairly common that a ship may leave with a few thousand of our containers.   This could result in a large batch as many of these containers would have the same BIC code (ocean carriers like to ship their own containers.)
