### ISSUE TITLE
API answers with wrong content

### ISSUE THREAD

**Issue by janmatysik** [bic-org/Boxtech#16]
Hi, I'm trying to use the API to get information about a container, but the answer is always HTML, not JSON.

Log:
Sending 'POST' request to URL : https://app.bic-boxtech.org/oauth/token
2018-08-24 12:52:30,299 [INFO] BicBoxtechService - Response Code : 200
2018-08-24 12:52:30,648 [INFO] BicBoxtechService - 
Sending 'GET' request to URL : https://app.bic-boxtech.org/api/container/GLDU5334260
2018-08-24 12:52:30,648 [INFO] BicBoxtechService - Response Code : 200
2018-08-24 12:52:35,876 [ERROR] BicBoxtechService - Error when trying to get container data from BIC. The answer was not JSON.

The answer from the server:
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8">
    <title>No such app</title>
    <style media="screen">          html, body, iframe {
        margin: 0;
        padding: 0;
    }

    html, body {
        height: 100%;
        overflow: hidden;
    }

    iframe {
        width: 100%;
        height: 100%;
        border: 0;
    }        </style>
</head>
<body>
<iframe src="//www.herokucdn.com/error-pages/no-such-app.html"></iframe>
</body>
</html>

What is wrong here? According to your API documentation, this should work.

**Comment by AltiusRupert** [comment]
Hi Jan,
As you can see in the Swagger definition
https://bic-boxtech.github.io/BIC-Boxtech-API-documentation/index.html
the endpoint ends with .../api/v2.0

I have updated the README to mention endpoint .../api/v2.0 instead of .../api

Please confirm that your test works correctly with the v2.0 endpoint URL.

Thanks,
Rupert

**Comment by janmatysik** [comment]
Hi Rupert, thank you for the very fast reply. I didn't see the change, sorry. I'm now getting a result but it looks different than in Swagger.


  {
    "bic_code": "HMMU",
    "prefix": "HMM",
    "equipment_identifier": "U",
    "serial_number": "605097",
    "check_digit": "1",
    "group_st": "4HDC",
    "detail_st": null,
    "tare_kg": 3700,
    "tare_lbs": null,
    "max_payload_kg": 28800,
    "max_payload_lbs": null,
    "max_gross_mass_kg": 32500,
    "max_gross_mass_lbs": null,
    "cubic_capacity_cbm": null,
    "cubic_capacity_cuft": null,
    "stacking_kg": null,
    "stacking_lbs": null,
    "racking_kg": null,
    "racking_lbs": null,
    "racking_n": null,
    "one_door_off_stacking_kg": null,
    "one_door_off_stacking_lbs": null,
    "one_door_off_racking_kg": null,
    "one_door_off_racking_lbs": null,
    "one_door_off_racking_n": null,
    "one_door_off_end_wall_strength_kg": null,
    "one_door_off_end_wall_strength_lbs": null,
    "manufacture_number": null,
    "manufacture_date": null,
    "manufacturer": null,
    "customs_approval": null,
    "customs_approval_type": null,
    "csc_approval": null,
    "timber_treatment_approval": null,
    "external_length_mm": null,
    "external_width_mm": null,
    "external_height_mm": null,
    "internal_length_mm": null,
    "internal_width_mm": null,
    "internal_height_mm": null,
    "door_opening_width_mm": null,
    "door_opening_height_mm": null,
    "container_number": "HMMU6050971",
    "checkDigitwarning": false,
    "external_length_ft": null,
    "internal_length_ft": null,
    "external_width_ft": null,
    "internal_width_ft": null,
    "external_height_ft": null,
    "internal_height_ft": null,
    "door_opening_width_ft": null,
    "door_opening_height_ft": null
  }

Best,
Jan

**Comment by AltiusRupert** [comment]
Congratulations !  ;)

We are in the processing of deploying a minor version with new container fields : they are not in the Swagger yet, since the formal deployment process is not yet complete.
So you have more fields than in the Swagger doc, but you have no Alert information ... because there are no alerts on this container !


I hope this addresses your worries,
Rupert

cc @BernierAltius
