### ISSUE TITLE
Container Alerts?

### ISSUE THREAD

**Issue by rwarren2** [bic-org/Boxtech#23]
In the swagger definition, there is nested json for alerts:

type | string
-- | --
description | string
message | string

Is there any documentation of what values of `type` can be?

**Comment by cmsdroff** [comment]
Hi @rwarren2 

I have updated the swagger spec at 

but the alert types are:

```
    - Sold
    - Scrapped
    - Security
    - Exception
```

Are you looking to create alerts in the Boxtech application (as n uploader) or just understand the alert types that come back (as a consumer)?

**Comment by rwarren2** [comment]
Just trying to understand the alerts as a consumer. Thank you.
