### ISSUE TITLE
response as json

### ISSUE THREAD

**Issue by stefanoCirillo** [bic-org/Boxtech#3]
We are interested to know as much information on the containers before they arrive at Terminal (for a correct vessel/yard planning) because when they enter/dishcharge will be inspected by us from our checker. Also the ROB (vessel remain on the board) container we need to know as much information.
We are looking for tare weight, max gross weight and iso syze-type code.
We use already many tools/data-flows to obtain this information. We want to integrate new tools…
We use kg.

**Comment by AltiusRupert** [comment]
We are planning to provide such an API entry point, but we would like to make it flexible and usable for all : 

**1) JSON answer**
The easiest would be to provide an entrypoint which would return a JSON structure with the available technical data.
In this case, how would you prefer to specify units : 
- should we have one entry point per unit (eg .../container_imperial vs .../container_metric) to return kgs, m, etc. vs lbs, ft, etc ?
- or should we have something more complex, like you passing as a parameter the list of fields you require (tare_kgs, height_ft, etc.) ?
- or even a single entry point and one answer with ALL units (eg tare_kgs, tare_lbs, height_m, height_ft, etc.) ?

**2) "simple" (non-JSON) answers**
Are you still interested in entry points which return a simple (non-JSON) answer, for 1 field only : eg .../tare_kgs returns only tare in kgs, with no JSON structure ?
Presumably, this might be interesting for older (legacy) programs which do not want to do any JSON parsing.

Your ideas ?

**Comment by stefanoCirillo** [comment]
We are only interested in the solution (1), a JSON answer, because it quickly retrieves all the information and our software are based on java that manage simple and fast json data.
We like (1-c) proposal with all units.

**Comment by AltiusRupert** [comment]
Stefano, just another point :

Each fleet owner who uploads their container data does not necessarily provide _all_ technical fields : tare is compulsory, but others are not.

Can your application work if some containers have this data, and some do not have all the data ?

**Comment by stefanoCirillo** [comment]
The Tara alone does not give us information to the recognition of a container.
So, we use first the iso size-type code for identify the container (20'/40' for example, reefer, etc..etc..).
Tara (ex. 2200) and max-gw (ex. 30480) will be revealed after anyway (by gate/vessel checker) and
override the original data (by data-flow).
Then, for us, the most important field is the iso size-type.

**Comment by AltiusRupert** [comment]
OK, so if I understand correctly, the following are very important data : 
- tare weight
- gross weight
- size type code

We will look into this and keep you posted.

Thanks, Stefano

cc @PierrickBrun

**Comment by sabas** [comment]
IMHO it should provide an entry point like /container
and ask for (optional) parameters in the request payload to allow filtering the response.

GET /container?number=CBHU1234567&unit=kg should return all available data in kilograms

**Comment by PierrickBrun** [comment]
Great idea, we are already thinking about it using units=metric or units=imperial.
We will come back to you when it is done

**Comment by rlarno** [comment]
Hi, we are very much interested in getting the size and type of a box via the API (in JSON format).
Since this issue is over a year old, is there any update about this?

**Comment by AltiusRupert** [comment]
Hi Rudi,
Thanks for being patient.
Boxtech v2 is going into acceptance tests phase, the API you need is included.
We will keep you posted in the next few weeks.

BR, Rupert

**Comment by BernierSFCloud** [comment]
Boxtech v2,0 has been released you can now get all the container detail in JSON format using the GET container endpoint. 

Please see the documentation :
https://github.com/bic-boxtech/BIC-BoxTech-API-Samples/wiki/V2.0-endpoints
