### ISSUE TITLE
HTTP 400 reCAPTCHA Error

### ISSUE THREAD

**Issue by isee-aeng** [bic-org/Boxtech#32]
Hello,

Following the BIC Boxtech API [Get Started here](https://bic-org.github.io/Boxtech/ManualTests/ManualTests.html) results in an HTTP 400 (Bad Request) error when attempting to retrieve the API access token:
```bash
{"message":"CAPTCHA does not match"}
```

Could you provide more information on how to resolve this? Thank you!

**Comment by clasbleiz** [comment]
Hello,

We have the same problem when trying to get a token : HTTP 400 Bad Request with body 
`{"message":"CAPTCHA does not match"}`

Are you aware of this issue ?

Thanks.

**Comment by craig-kotahi** [comment]
We have also started observing this issue yesterday.

**Comment by cmsdroff** [comment]
@isee-aeng @clasbleiz @craig-kotahi please check, this should be resolved for you now?  Thanks for reporting

**Comment by clasbleiz** [comment]
Yes, it's OK.
Thank you very much for your reactivity.

**Comment by cmsdroff** [comment]
Closing issue as issue resolved and now working as expected, please re-open if needed

**Comment by isee-aeng** [comment]
Thank you! Confirmed we are able to retrieve the token successfully now.
