### ISSUE TITLE
Boxtech - Migrating Service - Friday 30th 14:00 CET - ACTION REQUIRED.

### ISSUE THREAD

**Issue by cmsdroff** [bic-org/Boxtech#35]
Hi All, 

We are near completion of moving Boxtech to a Serverless environment and have made some changes to improve the experience, data quality, security and visual appearance of Boxtech.

To make the transition to the new environment simple and hopefully seamless we have retained the API Auth, and Endpoints that are in use, and we would like to request that you test your application in our UAT environment, this will be available from Monday 12th June until we make the changeover.

## IMPORTANT
As part of our security review you will be required to change your password to access Boxtech, so please take this opportunity to test and engage with us during the UAT.  It is planned that we will make the switchover for the end of July.  Final date will be communicated here following external testing phase.

## What we are looking for from you

Please register for the UAT environment: 
https://uat.bic-code.org/sign-up

Please test your application on the UAT url with your API
`https://uat.bic-boxtech.org/api/v2.0`

We would really like you to test the API within your application to ensure a smooth transition, please pay attention to: 
* Authentication - by changing the URL to UAT can you authenticate and access Boxtech?
* Endpoints - Please test all the endpoints you have coded into your application and confirm or advise if there are issues or differences in what you expect
* Dataset are all the fields that you are using contained within the response?  some fields from the `/web` endpoint and from `alert` response were designed to facilitate the Boxtech frontend only, you should be using `/api` endpoints only, these fields have been removed from the response.

Please raise any issues as GitHub issues or comments on this ticket so we can address and facilitate a smooth transition for your systems

## Notes
We didn't want to issue a breaking change to the API version so it will remain at V2, however as noted above some fields contained icons or visual code from the `web/`endpoints which were used in the frontend, there should not have been any need or use for these and the `web/` endpoint was internal, however it is important to check the responses are working in your applications to avoid any issues, please report by way of GitHub issue if this is problematic.

Some attributes were also using inconsistent formatting i.e. underscores or camelCase, we have standardised on the `_` and added in values to replace these, so camelCase attributes will eventually be deprecated in a future V3, but V2 will have both versions in with the recommendation to use the `_` value.

example: 
`checkDigitwarning`
recommended to use 
`check_digit_warning`

## Swagger Spec
The swagger spec can be found at https://app.swaggerhub.com/apis/BIC-ORG/Boxtech/2.0.2-dev

## Whilst your looking
We would really like to understand how Boxtech helps you and any feature requests you may have for Boxtech which maybe useful.  This is a first step to bring Boxtech into the revised digital offering from BIC along with the BIC Facility Codes (https://www.bic-code.org/bic-facility-codes/) to uniquely identify container facilities and BIC Code Owner API.

Your feedback helps us shape the BIC API's to support your needs, thanks in advance for your support.

**Comment by cmsdroff** [comment]
Dear @isee-aeng, @clasbleiz, @craig-kotahi, 

As you kindly raised some issues with the captcha previously, could I just highlight this to you to check the UAT environment would work in your applications, you should just need to register on UAT and change the URL (hopefully!) 

I have sent email to all API users registered addresses so hopefully you will have received that.

We will migrate Boxtech to AWS shortly and have re-written the code base to take into account security and future plans.

Would be great to get your feedback and confirmation that the new version will be ok within your applications, and all the endpoints you use are covered, any comments please let us know so we can advise or refactor anything.

Thanks in advance and have a good weekend!

**Comment by anghy23** [comment]
Dear @cmsdroff,

using RestSharp with .Net framework 4.5 I had to add the following line of code to make my app working:

_System.Net.ServicePointManager.SecurityProtocol = System.Net.SecurityProtocolType.Tls12;_

Otherwise I had the error : _The request was aborted: Could not create SSL/TLS secure channel_
See also https://stackoverflow.com/questions/30409048/restsharp-tls-1-1

Thanks

**Comment by cmsdroff** [comment]
> Dear @cmsdroff,
> 
> using RestSharp with .Net framework 4.5 I had to add the following line of code to make my app working:
> 
> _System.Net.ServicePointManager.SecurityProtocol = System.Net.SecurityProtocolType.Tls12;_
> 
> Otherwise I had the error : _The request was aborted: Could not create SSL/TLS secure channel_
> See also https://stackoverflow.com/questions/30409048/restsharp-tls-1-1
> 
> Thanks

Dear @anghy23 

Thanks for testing and providing your comments, very much appreciated, and also for taking time to highlight what you had to change to use TLS 1.2, we are indeed using the latest recommendation for TLS and I'm sure that your description will help others who may come across this in their applications.

Thanks again for your valuable input :) 👍

**Comment by cmsdroff** [comment]
> Dear @isee-aeng, @clasbleiz, @craig-kotahi,
> 
> As you kindly raised some issues with the captcha previously, could I just highlight this to you to check the UAT environment would work in your applications, you should just need to register on UAT and change the URL (hopefully!)
> 
> I have sent email to all API users registered addresses so hopefully you will have received that.
> 
> We will migrate Boxtech to AWS shortly and have re-written the code base to take into account security and future plans.
> 
> Would be great to get your feedback and confirmation that the new version will be ok within your applications, and all the endpoints you use are covered, any comments please let us know so we can advise or refactor anything.
> 
> Thanks in advance and have a good weekend!

Dear @isee-aeng, @clasbleiz, @craig-kotahi,

Just wondered if you had tried the UAT version of Boxtech in your applications?  We plan to move over at the end of this month, welcome your time to check all in order please?

Thanks David

**Comment by cmsdroff** [comment]
# Boxtech Go Live Friday 30th July 14:00 CET

Dear all, 

We will go Live on **Friday afternoon circa 14:00 (CET)** depending upon time for DNS changes.

Thanks for testing, and comments on TLS, I can see some users registered in the UAT environment and have queried the UAT version of Boxtech.  Tomorrow we will make live the production version on api.bic-boxtech.org and on Friday we will switch the dns over from app.bic-boxtech.org so we will be live Friday on the new platform in full.

As the audience here will be more API driven we will give you a choice to ease the migration path ahead of Friday:

1. Register on https://api.bic-boxtech.org/sign-up tomorrow (I will post here once DNS change is made).  We will leave your new account live and not force a password change on Friday, meaning less downtime to the Boxtech API.
2. Wait until Friday and you will receive an email which will force a password change when we migrate your account, you wont be able to access Boxtech until your password is changed on the web interface.

Option 2 will be the **default position**, any accounts not setup ahead of time will be in this path.  Here are the details on the process to change your password https://docs.bic-boxtech.org/web/change-password

If you need any help once the change is made please open a GitHub issue and we will be looking out for them and reply asap.

Heres the notice that we sent out, if you didn't receive this your account will not be migrated as the email account was non responsive

https://mailchi.mp/34d19b0cc8f6/boxtech-service-migration-notice-5134301

Thanks for your support and continued use of Boxtech

**Comment by cmsdroff** [comment]
Dear All, 

The url https://api.bic-boxtech.org is now active and ready for you to register as per the previous post, this will allow you to access the production version of Boxtech ahead of the switch over and update your systems.

If you do nothing you will be migrated by **option 2** meaning you will need to reset your password to continue using the API.

Thanks in advance,

**Comment by cmsdroff** [comment]
Dear All, 

Boxtech is now live on https://app.bic-boxtech.org you will be prompted to change your password to continue using the application.

Any questions please raise an issue.

Thanks for your time to test, 

Best Regards
