### ISSUE TITLE
Incomplete data

### ISSUE THREAD

**Issue by LouisAlbertAyongo** [bic-org/Boxtech#38]
Hello,
I work in a seaport and my job is to check the identity and especially the size of the containers.
Each month we work on a minimum of **15 000 container**s.
So you understand that the volume is important.

I have integrated the API in our management software and out of the total number of containers we operate, 7% do not have a size and **44% are not in the BIC database**, this is the problem we encounter during the monthly verifications. 

It seems that the BIC either doesn't update the database anymore, or the API limits the results it displays.

**44% I think is a very high value for a Global database.**
The idea of setting up the API is really good, but not all containers are available on the BIC database.

If you can help by updating your database that would be very encouraging.
If you need more elements to process this request I remain fully available to help.

**Comment by cmsdroff** [comment]
Hi @LouisAlbertAyongo 

Thanks for your comments and feedback above, we will shortly drop you an email as we would like to hear more about your use cases and to discuss the above.

We recently moved Boxtech to a new platform and made some changes in the way the data is managed, we have been working with the ocean carriers (and others) to improve the datasets and quality, we have in this revision been more strict in the uploads and what is allowed so these figures will certainly improve in the near future.  

To reassure you there is regular upload activity by container owners, not all upload their fleets and we are in discussion with those, so it would be good to look at some of your analysis and use cases to support the future development.

I have your contact details and we will be in touch by email shortly.  Thanks for reaching out very much appreciated.

**Comment by cmsdroff** [comment]
closing due to activity but happy to re-engage @LouisAlbertAyongo

**Comment by LouisAlbertAyongo** [comment]
Hello, I may come back to open the subject again but I'm still having the same problem with some containers still not being uploaded to your database. This is the case with the TTNU8900769 container.
![TTNU8900769](https://github.com/bic-org/Boxtech/assets/85788101/c6e89467-ef37-441a-9a9b-37649eb3d8b8)
![BOXTECH](https://github.com/bic-org/Boxtech/assets/85788101/12112383-8d87-4131-b31c-30cdba9e07b9)
