### ISSUE TITLE
Endpoint for querying tare availability per BIC code

### ISSUE THREAD

**Issue by sabas** [bic-org/Boxtech#4]
Something like /bic/CBHU should return true or false if there are containers marked with CBHUxxxxxxx in the database.

**Comment by AltiusRupert** [comment]
Hi Stefano,
Could you tell us what use case you have in mind for this ?
We don't necessarily want people to poll to know _what_ is in the database, but rather query the database for info.

How about this idea : you could register to receive a notification every time someone loads a CBHU container.

**Comment by sabas** [comment]
The containers I handle aren't yet in the system, so I would like to know when (and if) they'll be loaded in the database. (a notification would work but not for every single container :+1:  )

**Comment by BernierSFCloud** [comment]
You can access the list of uploaded fleets over here : https://www.bic-boxtech.org/fleet-uploaded/

there is no plan yet to make this list available through API
