### ISSUE TITLE
Endpoint for Owner ID

### ISSUE THREAD

**Issue by 1linux** [bic-org/Boxtech#5]
It would be nice to have an endpoint to get the cleartext name of an owners´s ID.

**Comment by AltiusRupert** [comment]
Hi Helmut, thanks for your inpu.
Would you like to elaborate by describing your preferred scenario or use case for this requirement ?

**Comment by BernierSFCloud** [comment]
#poke

**Comment by AltiusRupert** [comment]
Thanks Thorsten.  Clearly, that's the idea and a quick way to deserialize the JSON container data.

@1linux , what is your use case to retrive the ownerId of the container ?
Are you looking for information about the uploader ?  The company which owns the container ?  Other ?

**Comment by bic-boxtech** [comment]
@1linux im closing this issue due to the time, but if you need help please open a new issue and we will support you with this, the data you want is in the API.
