### ISSUE TITLE
I cannot call service

### ISSUE THREAD

**Issue by abutalibsh** [bic-org/Boxtech#6]
I keep getting this response:

Invalid grant: user credentials are invalid

I logged in/out with the same password successfully.  However, the service does not accept it. Should it be a different password?

Regards,

**Comment by AltiusRupert** [comment]
Hi,
As you just closed this issue right after opening it, I presume you have fixed your problem.

Can I help you in any other way ?
Regards,
Rupert

**Comment by abutalibsh** [comment]
Hi Rupert,

Following the manual test guide, I realized I was posting the
username/password for postman, so I closed the request.

Now I created a username/password on boxtech and use them to test the
service, but I am receiving the same response.

Thank you for your help.

Regards,
Ahmad

**Comment by AltiusRupert** [comment]
Hi Ahmad,
Happy to help you.

Please could you send me screen shots or text copies of your configuration and the error message you receive ?  What kind of user profile did you ask for on BoxTech : reader or uploader ?  Did you ask for this user/password on BoxTech production or sandbox ?
Which endpoint are you using to test the callout ?  Sandbox ( http://test-bic-container.herokuapp.com) or production ( http://app.bic-boxtech.org) ?

**Comment by abutalibsh** [comment]
Hi Rupert,

Thank you very much for above points. My account was on production, and I
was testing with Sandbox. I received the right response Now.

Might I say, your database is still not filled properly. I searched some
containers, and got no response for them. What is the status? Are you still
waiting for shipping lines to upload their data?

Cheers,

**Comment by AltiusRupert** [comment]
Hi Ahmad,
You are correct : they are currently uploading data at their own speed.

What data are you looking for in particular ?

Regards,
Rupert

**Comment by abutalibsh** [comment]
Hi Rupert,

I am searching EDI ISO codes such as 45G1. Some containers ISO Codes are
unidentified and I was hoping I could use the service to find them.

Best regards,

Ahmad
