### ISSUE TITLE
Is there an endpoint for Max payload?

### ISSUE THREAD

**Issue by jc92** [bic-org/Boxtech#7]
Hi,
I wanted to ask whether it is already possible to get the Max payload field via API ?
Or would it be possible to fill Max gross mass by as the sum of tare and payload ?

Thanks in advance,
Regards,
Jc

**Comment by BernierSFCloud** [comment]
Hi,

the endpoint is coming in V2.0 that will go live soon

**Comment by BernierSFCloud** [comment]
This has been delivered in v2,0 
please refer to the following documentation :
https://github.com/bic-boxtech/BIC-BoxTech-API-Samples/wiki/Tare-Weight

the field you are looking for is max_payload_kg or max_payload_lbs
